### ISSUE TITLE
Lepší logování

### ISSUE THREAD

**Issue by padak** [keboola/db-extractor-bundle#1]
Ahoj,
řeším [ticket](https://keboola.zendesk.com/agent/tickets/4357) a dost bych ocenil, kdyby v Orchestatoru byly lepší logy. Dneska je to plný informací, co uživatele nezajímají. Typy na vylepšení:
- vyhodit věci co jsou zřejmé - u OK resultu nepotřebuju mít `error: null`, `component:ex-db`, ...
- `_index`, `process`, `lockName`, `_type`, `project` (není nutný vědět projekt - koukam do něj), `terminatedBy` (když nebyl terminovaný), `nestingLevel`, prázdný `result`, apod. dát pryč

Naopak mi tam schází:
- proklik na config
- informace o tom co to dělalo:
  - log queries
  - jejich časy
  - kolik z nich vypadlo dat
  - apod. 

Teď není vůbec schůdné zjistit, na čem se prodloužil 4x čas běhu.

[Příklad](https://connection.keboola.com/admin/projects/489/orchestrations/46417958/jobs/166534846) jobu, na který koukám...

Díky za zvážení!

Padák

**Comment by padak** [comment]
A co se týče logů v Jobu, tak tam je taky "moc" diskrétních eventů, ale není tam vidět aktivita tý komponenty. Například [tady](https://connection.keboola.com/admin/projects/489/jobs/167254953?q=) je v 6:00:22 jeden event (378615553) který je divně popsaný (exporting to - co to dělalo a jak dlouho?) a další event je až za 2 hodiny (378642578) v 07:58:46 a ten trval 25 sec. 

Je dost netriviální, až nemožný, zjistit, co to ty 2 hodiny mezi 6am a 8am dělalo... Tohle bych rád vylepšil taky.

**Comment by Halama** [comment]
proklik na config tam vidím

**Comment by padak** [comment]
jj - máš pravdu! čuměl jsem odscrollovaně, na sekci parameters, tam to není
![image](https://cloud.githubusercontent.com/assets/1427901/12387093/5207ec86-bdca-11e5-9185-ab4a766477d7.png)

**Comment by Halama** [comment]
Stahovalo to `in.c-ex-db-main.warehouse_reservations `
![image](https://cloud.githubusercontent.com/assets/903531/12387097/59421152-bdca-11e5-9d77-5e491fc4c2aa.png)

**Comment by padak** [comment]
@Halama tak na dobu stahování zakládám vlastní Issue v https://github.com/keboola/db-extractor-bundle/issues/3 - už se to rozlejzá, vše je tam popsané. Tady bych to nechal zaměřené na čtivost informací co z toho k userům lezou.

**Comment by padak** [comment]
@Halama A díky za pomoc!

**Comment by ErikZigo** [comment]
Zaviram, tohle uz se nikde nepoziva. Na DB extractory pouzivame docker komponenty.
