### ISSUE TITLE
Warning jako Internal Error

### ISSUE THREAD

**Issue by padak** [keboola/db-extractor-bundle#2]
Ahoj,

[tady](https://connection.keboola.com/admin/projects/489/jobs/167183122?q=) je chyba 

`Warning: Error while sending QUERY packet. PID=13314`

která je Internal Error. Pokud víme, že je problém v připojení k serveru, bylo by super to poslat k userovi. Pokud je to něco jiného, prosím o prozkoumání.

Týká se to https://keboola.zendesk.com/agent/tickets/4357

P.

**Comment by MiroCillik** [comment]
Pozriem na to

**Comment by ErikZigo** [comment]
Zaviram, tohle uz se nikde nepoziva. Na DB extractory pouzivame docker komponenty.
