### ISSUE TITLE
Značné zpomalení extraktoru - od víkendu

### ISSUE THREAD

**Issue by padak** [keboola/db-extractor-bundle#3]
Tak i Logio hlásí velké zpomalení extrakcí. Všechno je spojené se stable.cz hostingem, ale teď tam padlo i Logio, které má vlastní servery někde jinde.

Jirka Tobolka to hlásí v ticketu [#4359](https://keboola.zendesk.com/agent/tickets/4359). Tady to eviduju jako **bug**, bo mě to přijde potenciálně problematický.

**Comment by MiroCillik** [comment]
Hmm, v extraktore sa ale nic nemenilo, takze to zrejme bude nejaky sietovy problem :/ Skumame to.

**Comment by MiroCillik** [comment]
https://www.evernote.com/l/ABy1AhR1gwhMaZKO0eF3GVRGH7FX2zNStV4

Tu je graf z ktoreho je vidiet, ze s najvacsou pravdepodobnostou je chyba na strane hostingu Stable.

**Comment by padak** [comment]
Díky @MiroCillik Zavírám!
p.s. super debug!
