### ISSUE TITLE
PgSQL extract retry can produce "There is already an active transaction" error

### ISSUE THREAD

**Issue by ErikZigo** [keboola/db-extractor-bundle#4]
This code begin transaction:

https://github.com/keboola/db-extractor-pgsql/blob/master/src/Keboola/DbExtractor/Extractor/PgSQL.php#L77

When query fails and extractor try export retry, there will be given error with open transaction

**Comment by MiroCillik** [comment]
Tento problem vznikal kvoli nespravnemu backoffu, to uz je vyriesene.
